### ISSUE TITLE
CSS3动画

### ISSUE THREAD

**Issue by wardenger** [newteo/team-blog-repo#10]
# transition

这里首先从transition的角度看看动画是怎样的，动画应该是从一个初始状态转换到最终状态，比如说，一个宽100，高100的蓝色矩形（初始状态），变成了宽200，高200的红色矩形（最终状态）。如果我们没有用transition属性，那么这种变化会是即使的。

``` html
<div class="rect"></div>
```

``` css
.rect {
  width: 100px;
  height: 100px;
  background: blue;
}
.rect:hover {
  width: 200px;
  height: 200px;
  background: red;
}
```

transition的作用就是定义这个变化过程应该怎么变化

``` html
<body>
    <div class="rect"></div>
</body>
```

``` css
.rect {
    border-style: solid;
    border-width: 1px;
    display: block;
    width: 100px;
    height: 100px;
    background-color: #0000FF;
    -webkit-transition: width 2s, height 2s, background-color 2s, -webkit-transform 2s;
    transition: width 2s, height 2s, background-color 2s, transform 2s;
}
.rect:hover {
    background-color: #FFCCCC;
    width: 200px;
    height: 200px;
    -webkit-transform: rotate(180deg);
    transform: rotate(180deg);
}
```

可以使用以下属性来具体定义transition

``` css
div {
  transition-property: width height background-color font-size left top color;
  transition-duration: 0.5s;
  transition-timing-function: ease;
  transition-delay: 1s;
}
```

也可以使用transition属性按照顺序来指定

``` css
div {
  transition: <property> <duration> <timing-function> <delay>;
}
```

还可以用addEventListener监听transition完成的时刻

``` js
addEventListener("transitionend", updateTransition, true);
```

心得：动画无非是从一种状态往另一种状态转化的过程，比如说由大变小，由红色变成蓝色，从这个位置到那个位置。

这里提到了一点，从这个位置到那个位置。如果是一个div，你没有设置它的position属性是absolute或者是relative，那么你该怎么去改变它的位置呢？
毕竟，我现在理解的就是 用javascript去操作dom的各种属性。
